-- ============================================================================
-- EV Battery Swap Station Digital Twin -- telemetry schema (PostgreSQL 17)
--
-- Generated by:  python -m telemetry schema
-- This file is a reviewable snapshot. In production, promote it into an
-- Alembic revision (alembic revision --autogenerate) so migrations are
-- versioned and reversible.
-- ============================================================================

CREATE TABLE vehicles (
	id BIGSERIAL NOT NULL, 
	vehicle_id VARCHAR(32) NOT NULL, 
	first_seen TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	last_seen TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	ingest_count BIGINT DEFAULT '0' NOT NULL, 
	last_error TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (vehicle_id)
);
CREATE INDEX ix_vehicles_last_seen ON vehicles (last_seen);
COMMENT ON TABLE vehicles IS 'Fleet dimension table';
CREATE TABLE vehicle_state (
	vehicle_id VARCHAR(32) NOT NULL, 
	soc NUMERIC(10, 3), 
	soh NUMERIC(10, 3), 
	odometer_km DOUBLE PRECISION, 
	residual_mileage_km DOUBLE PRECISION, 
	charge_cycles BIGINT, 
	battery_temp_c NUMERIC(10, 3), 
	min_cell_v NUMERIC(10, 3), 
	max_cell_v NUMERIC(10, 3), 
	max_temp_c NUMERIC(10, 3), 
	min_temp_c NUMERIC(10, 3), 
	regen_kwh DOUBLE PRECISION, 
	speed_kmh DOUBLE PRECISION, 
	total_power_kwh DOUBLE PRECISION, 
	charging_status SMALLINT, 
	battery_avg_temp_c NUMERIC(10, 3), 
	battery_total_v NUMERIC(10, 3), 
	battery_current_a NUMERIC(10, 3), 
	max_cell_v_cell_no SMALLINT, 
	min_cell_v_pack_no SMALLINT, 
	min_cell_v_cell_no SMALLINT, 
	max_temp_pack_no SMALLINT, 
	work_status VARCHAR(64), 
	latitude DOUBLE PRECISION, 
	longitude DOUBLE PRECISION, 
	last_updated TIMESTAMP WITH TIME ZONE, 
	ingested_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	raw_frame JSONB, 
	PRIMARY KEY (vehicle_id)
);
CREATE INDEX ix_vehicle_state_last_updated ON vehicle_state (last_updated);
CREATE INDEX ix_vehicle_state_charging ON vehicle_state (charging_status) WHERE charging_status = 1;
CREATE INDEX ix_vehicle_state_soh ON vehicle_state (soh);
CREATE INDEX ix_vehicle_state_soc ON vehicle_state (soc);
COMMENT ON TABLE vehicle_state IS 'Latest telemetry snapshot per vehicle (upserted)';
CREATE TABLE telemetry (
	id BIGSERIAL NOT NULL, 
	vehicle_id VARCHAR(32) NOT NULL, 
	observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	soc NUMERIC(10, 3), 
	soh NUMERIC(10, 3), 
	odometer_km DOUBLE PRECISION, 
	residual_mileage_km DOUBLE PRECISION, 
	charge_cycles BIGINT, 
	battery_temp_c NUMERIC(10, 3), 
	min_cell_v NUMERIC(10, 3), 
	max_cell_v NUMERIC(10, 3), 
	max_temp_c NUMERIC(10, 3), 
	min_temp_c NUMERIC(10, 3), 
	regen_kwh DOUBLE PRECISION, 
	speed_kmh DOUBLE PRECISION, 
	total_power_kwh DOUBLE PRECISION, 
	charging_status SMALLINT, 
	battery_avg_temp_c NUMERIC(10, 3), 
	battery_total_v NUMERIC(10, 3), 
	battery_current_a NUMERIC(10, 3), 
	max_cell_v_cell_no SMALLINT, 
	min_cell_v_pack_no SMALLINT, 
	min_cell_v_cell_no SMALLINT, 
	max_temp_pack_no SMALLINT, 
	work_status VARCHAR(64), 
	latitude DOUBLE PRECISION, 
	longitude DOUBLE PRECISION, 
	ingested_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_telemetry_vehicle_observed UNIQUE (vehicle_id, observed_at)
);
CREATE INDEX ix_telemetry_observed_at ON telemetry (observed_at);
COMMENT ON TABLE telemetry IS 'Immutable telemetry history, one row per vehicle reading';
