"use client";

import { useState } from "react";

import { Card, CardHeader, Hairline, PageHeading } from "@/components/ui/Surface";
import { Metric } from "@/components/ui/Metric";
import { Pill } from "@/components/ui/Pill";

const chart = [38, 48, 42, 58, 66, 54, 72, 64, 78, 70, 84, 68, 74, 60, 52, 62, 76, 88, 80, 92, 78, 66, 54, 46];

const bayRows = [
  ["Bay 01", "Battery 14", "86%", "Charging", "18 min"], ["Bay 02", "Battery 08", "64%", "Charging", "34 min"],
  ["Bay 03", "Battery 21", "100%", "Ready", "—"], ["Bay 04", "Battery 04", "—", "Available", "—"],
  ["Bay 05", "Battery 17", "42%", "Charging", "52 min"], ["Bay 06", "Battery 02", "100%", "Ready", "—"],
  ["Bay 07", "—", "—", "Available", "—"], ["Bay 08", "Battery 11", "28%", "Charging", "71 min"],
];
const chargerRows = [
  ["Charger A01", "DC Fast", "Charging", "Battery 14", "86%", "120 kW", "18 min"],
  ["Charger A02", "DC Fast", "Available", "—", "—", "—", "—"],
  ["Charger B01", "AC Slow", "Charging", "Battery 08", "64%", "22 kW", "34 min"],
  ["Charger B02", "DC Fast", "Maintenance", "—", "—", "—", "—"],
];
const dgRows = [["31 Aug 2026", "3.5 h", "42 L", "480 kWh", "Grid support"], ["24 Aug 2026", "1.8 h", "21 L", "250 kWh", "Planned test"], ["17 Aug 2026", "5.2 h", "64 L", "710 kWh", "Grid outage"]];
const healthRows = [["Battery 14", "94%", "92%", "Low", "Continue normal use"], ["Battery 08", "88%", "84%", "Medium", "Schedule inspection"], ["Battery 21", "97%", "96%", "Low", "Continue normal use"], ["Battery 04", "81%", "74%", "High", "Plan replacement"]];

function Status({ children }: { children: string }) {
  const tone = children === "Ready" || children === "Available" || children === "Online" || children === "Low" ? "ok" : children === "Maintenance" || children === "High" ? "danger" : children === "Medium" ? "warn" : "info";
  return <Pill tone={tone} dot>{children}</Pill>;
}
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  const [selected, setSelected] = useState("");
  return <div className="scroll-thin overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-surface-2 text-[10px] font-semibold uppercase tracking-[0.08em] text-ink-3"><tr>{headers.map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-line">{rows.map((row) => <tr key={row[0]} onClick={() => setSelected(row[0])} className={`cursor-pointer transition hover:bg-surface-2 ${selected === row[0] ? "bg-accent-soft" : ""}`}>{row.map((value, index) => <td key={`${row[0]}-${index}`} className="px-4 py-3 text-ink-2">{index === 2 && (value === "Ready" || value === "Available" || value === "Maintenance" || value === "Low" || value === "Medium" || value === "High") ? <Status>{value}</Status> : value}</td>)}</tr>)}</tbody></table>{selected && <p className="border-t border-line px-4 py-2 text-[11px] text-accent">Selected {selected}. Detailed live integration will open here.</p>}</div>;
}
function Bars() { return <div className="flex h-40 items-end gap-1.5 px-4 pb-4 pt-5">{chart.map((height, index) => <div key={index} className="group flex flex-1 flex-col items-center justify-end gap-1"><div className="w-full rounded-t bg-accent/75 transition hover:bg-accent" style={{ height: `${height}%` }} title={`${height}% utilization`} /><span className="text-[9px] text-ink-3">{index % 4 === 0 ? `${String(index).padStart(2, "0")}h` : ""}</span></div>)}</div>; }

function Header({ title, subtitle }: { title: string; subtitle: string }) { return <PageHeading title={title} subtitle={subtitle} actions={<Pill tone="warn" dot>{subtitle}</Pill>} />; }
function Overview({ items }: { items: Array<[string, string, string]> }) { return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{items.map(([label, value, tone]) => <Metric key={label} label={label} value={value} tone={tone as "ok" | "warn" | "info" | "neutral"} />)}</div>; }

export default function DraftWorkspace({ kind }: { kind: "swap" | "charging" | "dg" | "predictive" }) {
  if (kind === "swap") return <SwapDraft />;
  if (kind === "charging") return <ChargingDraft />;
  if (kind === "dg") return <DgDraft />;
  return <PredictiveDraft />;
}
function SwapDraft() { return <div className="space-y-4"><Header title="Swap Station" subtitle="Draft view • Live integration pending" /><Overview items={[["Station name", "Pune Central", "info"], ["Location", "Pune, Maharashtra", "neutral"], ["Operating status", "Online", "ok"], ["Slot capacity", "8 bays", "accent"]]} /><Card className="overflow-hidden"><CardHeader eyebrow="Station model" title="Pune swap station" description="A clean operational preview of bays, vehicle flow, and battery readiness." /><div className="canvas-dark relative mx-4 mb-4 overflow-hidden rounded-xl border border-line bg-[radial-gradient(circle_at_70%_20%,rgba(111,159,216,.24),transparent_35%),linear-gradient(135deg,#151d2a,#202a39)] p-6"><div className="grid min-h-[210px] place-items-center"><div className="grid w-full max-w-xl grid-cols-4 gap-3">{bayRows.map((row) => <div key={row[0]} className="rounded-lg border border-white/10 bg-white/5 p-3 text-white shadow-lg"><div className="mb-5 h-8 rounded bg-white/10" /><p className="text-[10px] text-white/60">{row[0]}</p><p className="mt-1 text-xs font-semibold">{row[2] === "—" ? "Open bay" : row[2] + " charged"}</p><div className="mt-3 h-1 rounded-full bg-white/10"><div className="h-full rounded-full bg-emerald-400" style={{ width: row[2] === "—" ? "0%" : row[2] }} /></div></div>)}</div></div></div></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader eyebrow="Bay status" title="Eight battery bays" /><Hairline /><Table headers={["Bay", "Battery", "Charge level", "Status", "Ready in"]} rows={bayRows} /></Card><Card><CardHeader eyebrow="Daily performance" title="Swap activity" /><Hairline /><div className="grid grid-cols-2 gap-3 p-4"><Metric label="Swaps today" value="184" tone="info" /><Metric label="Average swap time" value="4.8" unit=" min" tone="ok" /></div><Bars /></Card></div></div>; }
function ChargingDraft() { return <div className="space-y-4"><Header title="Charging Station" subtitle="Draft view • Live integration pending" /><Overview items={[["Total chargers", "24", "info"], ["Active charging", "11", "ok"], ["Available", "10", "accent"], ["Under maintenance", "3", "warn"]]} /><Card><CardHeader eyebrow="Charger fleet" title="Charger details" /><Hairline /><Table headers={["Charger", "Type", "Status", "Battery", "Charge level", "Power", "Ready in"]} rows={chargerRows} /></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader eyebrow="Power summary" title="Station power" /><div className="grid grid-cols-3 gap-3 p-4"><Metric label="Current draw" value="486" unit=" kW" tone="info" /><Metric label="Grid supply" value="420" unit=" kW" tone="ok" /><Metric label="DG supplement" value="66" unit=" kW" tone="warn" /></div></Card><Card><CardHeader eyebrow="Utilization" title="24-hour charging utilization" /><Bars /></Card></div></div>; }
function DgDraft() { return <div className="space-y-4"><Header title="DG" subtitle="Draft view • Historical data integration planned" /><Card><CardHeader eyebrow="Generator status" title="Pune backup generator" /><div className="grid grid-cols-2 gap-3 p-4 lg:grid-cols-5"><Metric label="Unit specification" value="500 kVA" tone="info" /><Metric label="Current status" value="Standby" tone="ok" /><Metric label="Fuel level" value="72" unit="%" tone="warn" /><Metric label="Last run" value="31 Aug 2026" tone="neutral" /><Metric label="Runtime this month" value="10.5" unit=" h" tone="neutral" /></div></Card><Card><CardHeader eyebrow="Historical usage" title="Monthly generator usage" /><Hairline /><Table headers={["Date", "Runtime", "Fuel used", "Power generated", "Trigger reason"]} rows={dgRows} /></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader eyebrow="Cost comparison" title="Profit and loss impact" /><div className="grid grid-cols-3 gap-3 p-4"><Metric label="Estimated DG cost this month" value="₹18,420" tone="danger" /><Metric label="Grid equivalent cost" value="₹11,780" tone="ok" /><Metric label="Cost difference" value="₹6,640" tone="warn" /></div></Card><Card padded><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-accent">Module objective</p><p className="mt-2 text-sm leading-relaxed text-ink-2">Turn historical generator data into predictive power-demand planning, grid-versus-DG optimization, and automated P&amp;L reporting.</p></Card></div></div>; }
function PredictiveDraft() { return <div className="space-y-4"><Header title="Predictive Analysis" subtitle="Draft view • Models under development" /><div className="grid gap-3 sm:grid-cols-2">{[["⌁", "Demand Forecasting", "Predict site load before the next operating window."], ["◇", "Predictive Maintenance", "Spot battery and charger issues before failure."], ["↝", "Route Pattern Analysis", "Turn carrier movement into safer, faster routes."], ["▥", "Power Consumption Forecast", "Plan grid and generator capacity ahead of demand."]].map(([icon, title, description]) => <Card key={title} padded><div className="flex items-start justify-between"><span className="text-2xl text-accent">{icon}</span><Pill tone="warn">In development</Pill></div><h2 className="mt-4 text-sm font-semibold text-ink">{title}</h2><p className="mt-1 text-xs leading-relaxed text-ink-2">{description}</p><button type="button" className="mt-4 cursor-pointer text-xs font-semibold text-accent hover:underline">Explore model →</button></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader eyebrow="Forecast preview" title="Expected site demand" /><Bars /></Card><Card><CardHeader eyebrow="Fleet health" title="Battery health prediction" /><Hairline /><Table headers={["Battery", "Current health", "Health in 30 days", "Risk level", "Recommended action"]} rows={healthRows} /></Card></div><Card padded><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-accent">Key insights</p><ul className="mt-3 space-y-2 text-sm text-ink-2"><li>• Four batteries are projected to remain above 90% health over the next 30 days.</li><li>• Evening demand peaks between 18:00 and 21:00; schedule charging earlier where possible.</li><li>• One pack needs an inspection plan before its next service cycle.</li></ul></Card></div>; }
